#!/usr/bin/env python
from datetime import datetime

# TODO: fix this, too sick and tired of this docker container to fix right now
action = 'push'
name = 'b-rainbow-mind-machine'
branch = 'gh-pages'
url = 'https://git.charlesreid1.com/charlesreid1/b-rainbow-mind-machine.git'

logfile = '/tmp/{action}-{name}-{branch}.log'.format(action=action, 
                                                    name=name, 
                                                    branch=branch)

f = open(logfile,'a')

f.write("\n")
f.write("-"*40)
f.write(datetime.now().strftime("%Y-%m-%d_%H-%M-%S"))
f.write("\n")

import subprocess
import os

# ------------------
# pages
#
# for a hypothetical repo "project":
# 
# .git dir:     /www/pages.charlesreid1.com/git.project
# htdocs dir:     /www/pages.charlesreid1.com/htdocs/project

root = '/www'
pages = 'pages.charlesreid1.com'

basedir = os.path.join(root,pages)
workdir = os.path.join(basedir,"htdocs",name)
gitdir = os.path.join(basedir,"git.%s"%(name))

if( os.path.isdir( gitdir ) 
and os.path.isdir( os.path.join(basedir,"htdocs")) ):
    # pull
    pullcmd = ["git","-C",basedir,"--git-dir=%s"%(gitdir),"--work-tree=%s"%(workdir),"pull","origin","gh-pages"]
    f.write("About to run the command:\n")
    f.write("    $ " + " ".join(pullcmd))
    f.write("\n")
    #subprocess.call(pullcmd)
    p = subprocess.Popen(pullcmd, stdout=subprocess.STDERR, stderr=subprocess.PIPE)
    f.write(p.stderr().read())

else:
    # clone
    mkdircmd = ["mkdir","-p",basedir]
    clonecmd = ["git","-C",basedir,"clone","--separate-git-dir=%s"%(gitdir),"-b","gh-pages",url,workdir]
    f.write("About to run the command:\n")
    f.write("    $ " + " ".join(clonecmd))
    f.write("\n")
    #subprocess.call(clonecmd)
    p = subprocess.Popen(clonecmd, stdout=subprocess.STDERR, stderr=subprocess.PIPE)
    f.write(p.stderr().read())

f.close()
